### ISSUE TITLE
Put on hackage and stackage?

### ISSUE THREAD

**Issue by minad** [dmoverton/finite-domain#1]

**Comment by dmoverton** [comment]
Hi Minad,

Putting this on Hackage is something I'd like to do. Unfortunately your request came in the same day my daughter was born and I have not had a chance to do anything about it yet.

David

**Comment by minad** [comment]
Oh, Congratulations then!

If you find time in the future to publish it, that would be great. Currently I am using a stripped down fork in a project. I use it to solve universe constraints in a stratified type hierarchy. But maybe in this case a graph based algorithm would be more efficient.

**Comment by dmoverton** [comment]
Cool. I'm glad you're finding it useful.

However, I developed it mainly as a pedagogical exercise. I don't expect it to be particularly efficient. There should be far faster constraint solvers out there.

**Comment by minad** [comment]
Yes, it is a really nice how it uses the list monad. And also simple to use and get started. Later on one can still switch to a different solver if necessary.
